--- 
version: "3.8"
services: 
  karate-tests: 
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: karate-tests
    volumes: 
      - "./target:/usr/src/app/target"
      - "~/.m2:/root/.m2"
    command: mvn test
